### ISSUE TITLE
Make browser tab title change to the title of the puzzle

### ISSUE THREAD

**Issue by Tuttleturtle** [rtc-hunt/hunt-masterlist#11]
Currently all tabs say 'Hunt Master List" even when open to different puzzles (or the master list home page) - if we have them change to the puzzle you are on, that would make it easier to be working on multiple puzzles on different pages simultaneously, swapping between them.

**Comment by jonored** [comment]
Done in 191da91cbfbda9bec47a115877f48990e1139128
